# Generated by Django 2.0 on 2019-09-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portrait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yxbj', models.CharField(max_length=50, verbose_name='院系班级名称')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addinfo', to='warning.Spinner', verbose_name='上一级学院的id')),
            ],
            options={
                'db_table': 'Spinner',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszBzx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('bzxts', models.IntegerField(default=0, verbose_name='不在校天数')),
                ('yjms', models.CharField(max_length=512, verbose_name='预警描述')),
                ('by1', models.CharField(max_length=32, verbose_name='备用1')),
                ('by2', models.CharField(max_length=32, verbose_name='备用2')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之不在校预警修改',
                'verbose_name_plural': '预警阈值设置之不在校预警修改',
                'db_table': 'yjyzsz_bzxyj',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszTk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkyj', models.CharField(max_length=32, verbose_name='逃课预警')),
                ('tks', models.IntegerField(default=0, verbose_name='逃课数')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之逃课预警修改',
                'verbose_name_plural': '预警阈值设置之逃课预警修改',
                'db_table': 'yjyzsz_tkxw',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszWgyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('wgsj', models.DateTimeField(verbose_name='晚归时间')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之晚归预警修改',
                'verbose_name_plural': '预警阈值设置之晚归预警修改',
                'db_table': 'yjyzsz_wg',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszXwzs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('xwzsts', models.IntegerField(default=0, verbose_name='校外住宿天数')),
                ('by1', models.CharField(max_length=32, verbose_name='备用1')),
                ('by2', models.CharField(max_length=32, verbose_name='备用2')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之校外住宿预警修改',
                'verbose_name_plural': '预警阈值设置之校外住宿预警修改',
                'db_table': 'yjyzsz_xwzs',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszXxtxblx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('xxtxblxdj', models.IntegerField(default=0, verbose_name='休学退学不离校等级')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之休学退学不离校预警修改',
                'verbose_name_plural': '预警阈值设置之休学退学不离校预警修改',
                'db_table': 'yjyzsz_xxtxblx',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszZjzxbxk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之在籍在校不选课预警修改',
                'verbose_name_plural': '预警阈值设置之在籍在校不选课预警修改',
                'db_table': 'yjyzsz_zjzxbxk',
            },
        ),
        migrations.CreateModel(
            name='XwgjGrgj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('gj', models.CharField(max_length=64, null=True)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grgj', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '行为轨迹之个人轨迹',
                'verbose_name_plural': '行为轨迹之个人轨迹',
                'db_table': 'xwgj_grgj',
            },
        ),
        migrations.CreateModel(
            name='ZnyjBzx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('yjrq', models.DateTimeField(auto_now_add=True, verbose_name='预警日期')),
                ('bzxsj', models.CharField(max_length=32, verbose_name='不在校时间')),
                ('bzxsc', models.IntegerField(default=0, verbose_name='不在校时长')),
                ('yjdj', models.IntegerField(choices=[(0, '黄'), (1, '橙'), (2, '红')], default=0)),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bzx', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警之不在校预警',
                'verbose_name_plural': '智能预警之不在校预警',
                'db_table': 'znyj_bzxyj',
            },
        ),
        migrations.CreateModel(
            name='ZnyjSwxw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('syll', models.FloatField(default=0.0, null=True, verbose_name='使用流量')),
                ('yjdj', models.IntegerField(choices=[(0, '黄'), (1, '橙'), (2, '红')], default=0)),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swxw', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警之上网行为',
                'verbose_name_plural': '智能预警之上网行为',
                'db_table': 'znyj_swxw',
            },
        ),
        migrations.CreateModel(
            name='ZnyjTkxw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('yjrq', models.DateTimeField(auto_now_add=True, verbose_name='预警日期')),
                ('kcsd', models.CharField(max_length=32, verbose_name='课程时段')),
                ('kcmc', models.CharField(max_length=64, verbose_name='课程名称')),
                ('yjqk', models.CharField(max_length=64, verbose_name='预警情况')),
                ('yjdj', models.IntegerField(choices=[(0, '黄'), (1, '橙'), (2, '红')], default=0)),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tkxw', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警之逃课行为预警',
                'verbose_name_plural': '智能预警之逃课行为预警',
                'db_table': 'znyj_tkxw',
            },
        ),
        migrations.CreateModel(
            name='ZnyjWgyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('yjrq', models.DateTimeField(auto_now_add=True, verbose_name='预警日期')),
                ('wgrq', models.DateTimeField(auto_now_add=True, verbose_name='晚归日期')),
                ('yjqk', models.CharField(max_length=64, null=True, verbose_name='预警情况')),
                ('yjdj', models.IntegerField(choices=[(0, '黄'), (1, '橙'), (2, '红')], default=0)),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wg', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警--晚归宿预警',
                'verbose_name_plural': '智能预警--晚归宿预警',
                'db_table': 'znyj_wg',
            },
        ),
        migrations.CreateModel(
            name='ZnyjXwzsyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('yjrq', models.DateTimeField(auto_now_add=True, verbose_name='预警日期')),
                ('xwzsts', models.IntegerField(default=0, null=True, verbose_name='校外住宿天数')),
                ('ycqk', models.CharField(max_length=32, null=True, verbose_name='预警情况')),
                ('yjdj', models.IntegerField(choices=[(0, '黄'), (1, '橙'), (2, '红')], default=0)),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xwzs', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警--校外住宿预警',
                'verbose_name_plural': '智能预警--校外住宿预警',
                'db_table': 'znyj_xwzs',
            },
        ),
        migrations.CreateModel(
            name='ZnyjXxtxblx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('yjrq', models.DateTimeField(auto_now_add=True, verbose_name='预警日期')),
                ('txxx', models.DateField(auto_now_add=True, null=True, verbose_name='退学休学日期')),
                ('yjqk', models.CharField(max_length=32, null=True, verbose_name='预警情况')),
                ('yjdj', models.IntegerField(choices=[(0, '黄'), (1, '橙'), (2, '红')], default=0, null=True)),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xxtxblx', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警之休学退学不离校预警',
                'verbose_name_plural': '智能预警之休学退学不离校预警',
                'db_table': 'znyj_xxtxblx',
            },
        ),
        migrations.CreateModel(
            name='ZnyjZjzxbxk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('yjrq', models.DateTimeField(auto_now_add=True, verbose_name='预警日期')),
                ('sjxf', models.IntegerField(default=0, null=True, verbose_name='实际学分')),
                ('yxxf', models.IntegerField(default=0, null=True, verbose_name='应修学分')),
                ('wxkxq', models.CharField(max_length=32, null=True, verbose_name='未选课学期')),
                ('clzt', models.IntegerField(choices=[(0, '未处理'), (1, '确认预警'), (2, '取消预警')], default=0)),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zjzxbxk', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '智能预警--在籍在校不选课预警',
                'verbose_name_plural': '智能预警--在籍在校不选课预警',
                'db_table': 'znyj_zjzxbxk',
            },
        ),
    ]
