# Generated by Django 2.0 on 2019-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0002_xtglyjyzszzjzxbxk_zjzxbxk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglyjyzszzjzxbxk',
            name='zjzxbxk',
        ),
        migrations.AddField(
            model_name='xtglyjyzszzjzxbxk',
            name='zjzxbxkjs',
            field=models.IntegerField(default=0, verbose_name='在籍在校不选课节数'),
        ),
    ]
