# Generated by Django 2.0 on 2019-09-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0004_auto_20190903_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xtglyjyzsztk',
            old_name='tkyj',
            new_name='yjmc',
        ),
    ]
