# Generated by Django 2.0 on 2019-09-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0006_auto_20190903_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XtglYjyzszBzx',
        ),
        migrations.DeleteModel(
            name='XtglYjyzszTk',
        ),
        migrations.DeleteModel(
            name='XtglYjyzszWgyj',
        ),
        migrations.DeleteModel(
            name='XtglYjyzszXwzs',
        ),
        migrations.DeleteModel(
            name='XtglYjyzszXxtxblx',
        ),
        migrations.DeleteModel(
            name='XtglYjyzszZjzxbxk',
        ),
    ]
