# Generated by Django 2.0 on 2019-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0007_auto_20190903_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='XtglYjyzsz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
            ],
        ),
        migrations.CreateModel(
            name='XtglYjyzszBzx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('red', models.IntegerField(default=0, verbose_name='红色等级天数')),
                ('orange', models.IntegerField(default=0, verbose_name='橙色等级天数')),
                ('yellow', models.IntegerField(default=0, verbose_name='黄色等级天数')),
                ('yjms', models.CharField(max_length=512, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之不在校预警修改',
                'verbose_name_plural': '预警阈值设置之不在校预警修改',
                'db_table': 'yjyzsz_bzxyj',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszTk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='逃课预警')),
                ('tks', models.IntegerField(default=0, verbose_name='逃课数')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之逃课预警修改',
                'verbose_name_plural': '预警阈值设置之逃课预警修改',
                'db_table': 'yjyzsz_tkxw',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszWgyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('red', models.CharField(max_length=32, verbose_name='等级红时间段')),
                ('orange', models.CharField(max_length=32, verbose_name='等级橙色时间段')),
                ('yellow', models.CharField(max_length=32, verbose_name='等级黄色时间段')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之晚归预警修改',
                'verbose_name_plural': '预警阈值设置之晚归预警修改',
                'db_table': 'yjyzsz_wg',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszXwzs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('red', models.IntegerField(default=0, verbose_name='红色等级天数')),
                ('orange', models.IntegerField(default=0, verbose_name='橙色等级天数')),
                ('yellow', models.IntegerField(default=0, verbose_name='黄色等级天数')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之校外住宿预警修改',
                'verbose_name_plural': '预警阈值设置之校外住宿预警修改',
                'db_table': 'yjyzsz_xwzs',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszXxtxblx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('red', models.IntegerField(default=0, verbose_name='红色等级天数')),
                ('orange', models.IntegerField(default=0, verbose_name='橙色等级天数')),
                ('yellow', models.IntegerField(default=0, verbose_name='黄色等级天数')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之休学退学不离校预警修改',
                'verbose_name_plural': '预警阈值设置之休学退学不离校预警修改',
                'db_table': 'yjyzsz_xxtxblx',
            },
        ),
        migrations.CreateModel(
            name='XtglYjyzszZjzxbxk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('zjzxbxkjs', models.IntegerField(default=0, verbose_name='在籍在校不选课节数')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置之在籍在校不选课预警修改',
                'verbose_name_plural': '预警阈值设置之在籍在校不选课预警修改',
                'db_table': 'yjyzsz_zjzxbxk',
            },
        ),
    ]
