# Generated by Django 2.0 on 2019-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0008_xtglyjyzsz_xtglyjyzszbzx_xtglyjyzsztk_xtglyjyzszwgyj_xtglyjyzszxwzs_xtglyjyzszxxtxblx_xtglyjyzszzjzx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XtglYjyzsz',
        ),
        migrations.AlterField(
            model_name='xtglyjyzszwgyj',
            name='create_user',
            field=models.CharField(max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='xtglyjyzszzjzxbxk',
            name='create_user',
            field=models.CharField(max_length=32, null=True, verbose_name='创建者ID'),
        ),
    ]
