# Generated by Django 2.0 on 2019-09-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0009_auto_20190904_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='XtglYjyzsz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置',
                'verbose_name_plural': '预警阈值设置',
                'db_table': 'yjyzsz',
            },
        ),
        migrations.AddField(
            model_name='xtglyjyzszzjzxbxk',
            name='xtglyjsz',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='warning.XtglYjyzsz'),
        ),
    ]
