# Generated by Django 2.0 on 2019-09-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0010_auto_20190904_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglyjyzszzjzxbxk',
            name='xtglyjsz',
        ),
    ]
