# Generated by Django 2.0 on 2019-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0011_remove_xtglyjyzszzjzxbxk_xtglyjsz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XtglYjyzsz',
        ),
    ]
