# Generated by Django 2.0 on 2019-09-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0012_delete_xtglyjyzsz'),
    ]

    operations = [
        migrations.CreateModel(
            name='XtglYjyzsz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='唯一标识')),
                ('yjmc', models.CharField(max_length=32, verbose_name='预警名称')),
                ('red', models.CharField(max_length=32, null=True, verbose_name='红色等级')),
                ('orange', models.CharField(max_length=32, null=True, verbose_name='橙色等级')),
                ('yellow', models.CharField(max_length=32, null=True, verbose_name='黄色等级')),
                ('zjzxbxkjs', models.IntegerField(default=0, verbose_name='在籍在校不选课节数')),
                ('tks', models.IntegerField(default=0, verbose_name='逃课数')),
                ('yjms', models.CharField(max_length=512, null=True, verbose_name='预警描述')),
                ('kqzt', models.IntegerField(default=0, verbose_name='开启状态')),
                ('create_user', models.CharField(max_length=32, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警阈值设置',
                'verbose_name_plural': '预警阈值设置',
                'db_table': 'yjyzsz',
            },
        ),
    ]
