# Generated by Django 2.0 on 2019-09-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0013_xtglyjyzsz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='znyjxwzsyj',
            old_name='ycqk',
            new_name='yjqk',
        ),
    ]
