# Generated by Django 2.0 on 2019-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0014_auto_20190911_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znyjzjzxbxk',
            name='yjrq',
            field=models.DateField(verbose_name='预警日期'),
        ),
    ]
