# Generated by Django 2.0 on 2019-09-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0015_auto_20190911_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='znyjwgyj',
            old_name='yjqk',
            new_name='ycqk',
        ),
    ]
