# Generated by Django 2.0 on 2019-09-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0016_auto_20190916_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='znyjwgyj',
            old_name='ycqk',
            new_name='yjqk',
        ),
    ]
