# Generated by Django 2.0 on 2019-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0017_auto_20190917_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znyjswxw',
            name='clzt',
        ),
        migrations.RemoveField(
            model_name='znyjswxw',
            name='yjdj',
        ),
    ]
