# Generated by Django 2.0 on 2019-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0018_auto_20190917_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znyjwgyj',
            name='yjqk',
            field=models.IntegerField(choices=[(1, '宿舍楼刷卡进入'), (2, '宿舍楼刷卡出'), (3, '网络连接'), (4, '宿舍楼以外区域刷E卡')], default=0, verbose_name='预警情况'),
        ),
    ]
