# Generated by Django 2.0 on 2019-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0019_auto_20190917_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglyjyzsz',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglyjyzszbzx',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglyjyzsztk',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglyjyzszwgyj',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglyjyzszxwzs',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglyjyzszxxtxblx',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglyjyzszzjzxbxk',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xwgjgrgj',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjbzx',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjswxw',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjtkxw',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjwgyj',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjxwzsyj',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjxxtxblx',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='znyjzjzxbxk',
            name='create_user',
        ),
    ]
