# Generated by Django 2.0 on 2019-09-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0022_auto_20190919_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglyjyzsz',
            name='zjzxbxkjs',
        ),
    ]
