# Generated by Django 2.0 on 2019-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0023_remove_xtglyjyzsz_zjzxbxkjs'),
    ]

    operations = [
        migrations.AddField(
            model_name='znyjswxw',
            name='swsj',
            field=models.DateField(null=True, verbose_name='上网时间'),
        ),
    ]
