# Generated by Django 2.0 on 2019-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0025_auto_20190923_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znyjwgyj',
            name='wgrq',
        ),
        migrations.RemoveField(
            model_name='znyjwgyj',
            name='yjrq',
        ),
        migrations.AddField(
            model_name='znyjwgyj',
            name='wgsj',
            field=models.DateTimeField(null=True, verbose_name='晚归时间'),
        ),
        migrations.AddField(
            model_name='znyjwgyj',
            name='yjsj',
            field=models.DateTimeField(null=True, verbose_name='预警时间'),
        ),
    ]
