# Generated by Django 2.0 on 2019-09-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0026_auto_20190923_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xwgjgrgj',
            name='user',
        ),
        migrations.DeleteModel(
            name='XwgjGrgj',
        ),
    ]
