# Generated by Django 2.0 on 2019-09-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0025_auto_20190921_1735'),
        ('warning', '0027_auto_20190923_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, null=True, verbose_name='班级代码')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
                'db_table': 'bzks_bj',
            },
        ),
        migrations.CreateModel(
            name='Nj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, null=True, verbose_name='年级代码')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='年级名称')),
            ],
            options={
                'verbose_name': '年级表',
                'verbose_name_plural': '年级表',
                'db_table': 'bzks_nj',
            },
        ),
        migrations.CreateModel(
            name='XwgjGrgj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32)),
                ('xwsj', models.DateTimeField(null=True, verbose_name='行为时间')),
                ('xwdd', models.CharField(max_length=64, null=True, verbose_name='行为地点')),
                ('jd', models.CharField(max_length=64, null=True, verbose_name='经度')),
                ('wd', models.CharField(max_length=64, null=True, verbose_name='纬度')),
                ('by1', models.CharField(max_length=32, null=True, verbose_name='备用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grgj', to='portrait.UibeBzks')),
            ],
            options={
                'verbose_name': '行为轨迹个人轨迹',
                'verbose_name_plural': '行为轨迹个人轨迹',
                'db_table': 'xwgj_grgj',
            },
        ),
        migrations.CreateModel(
            name='Yx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, null=True, verbose_name='院系代码')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='院系名称')),
            ],
            options={
                'verbose_name': '院系表',
                'verbose_name_plural': '院系表',
                'db_table': 'bzks_yx',
            },
        ),
        migrations.AddField(
            model_name='nj',
            name='p_yx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nj', to='warning.Yx'),
        ),
        migrations.AddField(
            model_name='bj',
            name='p_nj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bj', to='warning.Nj'),
        ),
    ]
