# Generated by Django 2.0 on 2019-09-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0028_auto_20190923_1012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xtglyjyzsz',
            table='xtgl_yjyzsz',
        ),
    ]
