# Generated by Django 2.0 on 2019-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0029_auto_20190924_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znyjzjzxbxk',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
