# Generated by Django 2.0 on 2019-12-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0030_auto_20191216_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znyjzjzxbxk',
            name='by1',
        ),
    ]
