# Generated by Django 2.0 on 2019-12-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0032_auto_20191225_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bj',
            name='p_nj',
        ),
        migrations.RemoveField(
            model_name='nj',
            name='p_yx',
        ),
        migrations.DeleteModel(
            name='Bj',
        ),
        migrations.DeleteModel(
            name='Nj',
        ),
        migrations.DeleteModel(
            name='Yx',
        ),
    ]
