# Generated by Django 2.0 on 2019-12-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0033_auto_20191226_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xwgjgrgj',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='znyjbzx',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='znyjswxw',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='znyjtkxw',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='znyjxwzsyj',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='znyjxxtxblx',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='znyjxxtxblx',
            name='txxx',
        ),
        migrations.AddField(
            model_name='znyjxxtxblx',
            name='blxsc',
            field=models.IntegerField(default=0, verbose_name='不离校时长'),
        ),
        migrations.AddField(
            model_name='znyjxxtxblx',
            name='blxsj',
            field=models.CharField(max_length=32, null=True, verbose_name='不离校时间'),
        ),
        migrations.AddField(
            model_name='znyjxxtxblx',
            name='ydrq',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='异动日期'),
        ),
    ]
