# Generated by Django 2.0 on 2019-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0034_auto_20191230_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='znyjxwzsyj',
            name='xwzssj',
            field=models.CharField(max_length=32, null=True, verbose_name='校外住宿时长'),
        ),
    ]
