# Generated by Django 2.0 on 2019-12-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0035_znyjxwzsyj_xwzssj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znyjzjzxbxk',
            name='user',
        ),
    ]
