# Generated by Django 2.0 on 2019-12-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0063_auto_20191230_1042'),
        ('warning', '0036_remove_znyjzjzxbxk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='znyjzjzxbxk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zjzxbxk', to='portrait.UibeBzks'),
        ),
    ]
