# Generated by Django 2.0 on 2019-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0038_auto_20191230_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znyjxxtxblx',
            name='yjqk',
            field=models.CharField(max_length=256, null=True, verbose_name='预警情况'),
        ),
    ]
