# Generated by Django 2.0 on 2020-04-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0040_znyjtkxw_yjsj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinner',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Spinner',
        ),
    ]
