# Generated by Django 2.0 on 2020-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0041_auto_20200410_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xwgjgrgj',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
