# Generated by Django 2.0 on 2020-06-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0073_auto_20200416_1002'),
        ('warning', '0042_auto_20200603_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='JzgXwgjGrgj',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('zgh', models.CharField(max_length=32, verbose_name='职工号')),
                ('xwsj', models.DateTimeField(null=True, verbose_name='行为时间')),
                ('xwdd', models.CharField(max_length=64, null=True, verbose_name='行为地点')),
                ('jd', models.CharField(max_length=64, null=True, verbose_name='经度')),
                ('wd', models.CharField(max_length=64, null=True, verbose_name='纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grgj', to='portrait.UibeJzg')),
            ],
            options={
                'verbose_name': '行为轨迹教职工个人轨迹',
                'verbose_name_plural': '行为轨迹教职工个人轨迹',
                'db_table': 'xwgj_jzg_grgj',
            },
        ),
        migrations.AlterField(
            model_name='xwgjgrgj',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grgj', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjbzx',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bzx', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjswxw',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swxw', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjtkxw',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkxw', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjwgyj',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjxwzsyj',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xwzs', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjxxtxblx',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xxtxblx', to='portrait.UibeBzks'),
        ),
        migrations.AlterField(
            model_name='znyjzjzxbxk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zjzxbxk', to='portrait.UibeBzks'),
        ),
    ]
