# Generated by Django 2.0 on 2020-06-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0075_uibeyjs'),
        ('warning', '0043_auto_20200609_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='YjsXwgjGrgj',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32, verbose_name='学号')),
                ('xwsj', models.DateTimeField(null=True, verbose_name='行为时间')),
                ('xwdd', models.CharField(max_length=64, null=True, verbose_name='行为地点')),
                ('jd', models.CharField(max_length=64, null=True, verbose_name='经度')),
                ('wd', models.CharField(max_length=64, null=True, verbose_name='纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grgj', to='portrait.UibeYjs')),
            ],
            options={
                'verbose_name': '行为轨迹研究生个人轨迹',
                'verbose_name_plural': '行为轨迹研究生个人轨迹',
                'db_table': 'xwgj_yjs_grgj',
            },
        ),
    ]
