# Generated by Django 2.0 on 2020-06-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0044_yjsxwgjgrgj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znyjtkxw',
            name='yjdj',
        ),
    ]
