# Generated by Django 2.0 on 2020-09-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0045_remove_znyjtkxw_yjdj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='znyjbzx',
            name='user',
        ),
    ]
