# Generated by Django 2.0 on 2020-09-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0079_bzkscetmiddle'),
        ('warning', '0046_remove_znyjbzx_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='znyjbzx',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bzx', to='portrait.UibeBzks'),
        ),
    ]
