# Generated by Django 2.0 on 2020-01-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_role_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='status',
        ),
    ]
