# Generated by Django 2.0 on 2020-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_role_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.BooleanField(choices=[(1, '启用'), (2, '停用')], default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态'),
        ),
    ]
