# Generated by Django 2.0 on 2020-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200423_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '教职工'), (2, '学生')], default=1, verbose_name='用户类型'),
        ),
    ]
