# Generated by Django 2.0 on 2019-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibebzks',
            name='xb',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0),
        ),
    ]
