# Generated by Django 2.0 on 2019-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0002_auto_20190902_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xtgljq',
            old_name='jssj',
            new_name='jqjssj',
        ),
        migrations.RenameField(
            model_name='xtgljq',
            old_name='kssj',
            new_name='jqkssj',
        ),
        migrations.AlterField(
            model_name='xtglbqsz',
            name='create_user',
            field=models.CharField(max_length=32, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='xtgljq',
            name='create_user',
            field=models.CharField(max_length=32, null=True, verbose_name='创建者'),
        ),
    ]
