# Generated by Django 2.0 on 2019-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0005_auto_20190903_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglbqwd',
            name='zt',
        ),
        migrations.AddField(
            model_name='xtglbqwd',
            name='kqzt',
            field=models.IntegerField(default=0, verbose_name='开启状态'),
        ),
    ]
