# Generated by Django 2.0 on 2019-09-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0006_auto_20190903_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sjzb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwbm', models.CharField(max_length=32, verbose_name='中文表名')),
                ('ywbm', models.CharField(max_length=32, verbose_name='英文表名')),
            ],
            options={
                'verbose_name': '系统管理之数据总表',
                'verbose_name_plural': '系统管理之数据总表',
                'db_table': 'xtgl_sjzb',
            },
        ),
        migrations.CreateModel(
            name='Sjzbzd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwzdmc', models.CharField(max_length=32, verbose_name='中文字段名')),
                ('zdsjbbs', models.CharField(max_length=32, verbose_name='字段数据表标识')),
                ('sjlx', models.CharField(max_length=32, verbose_name='数据类型')),
                ('bz', models.CharField(max_length=32, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sjzb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portrait.Sjzb')),
            ],
            options={
                'verbose_name': '系统管理之数据总表字段',
                'verbose_name_plural': '系统管理之数据总表字段',
                'db_table': 'xtgl_sjzbzd',
            },
        ),
    ]
