# Generated by Django 2.0 on 2019-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0008_auto_20190905_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='uibejzg',
            name='xznj',
            field=models.CharField(max_length=64, null=True, verbose_name='现在年级'),
        ),
        migrations.AddField(
            model_name='uibejzg',
            name='yx',
            field=models.CharField(max_length=64, null=True, verbose_name='院系'),
        ),
    ]
