# Generated by Django 2.0 on 2019-09-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0009_auto_20190909_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtglzbx',
            name='sjbxzs',
            field=models.CharField(max_length=32, null=True, verbose_name='数据表选择'),
        ),
        migrations.AlterField(
            model_name='xtglzbx',
            name='zbfl',
            field=models.IntegerField(choices=[(1, '单字段指标项'), (2, '多字段指标项')], default=1, verbose_name='指标分类'),
        ),
        migrations.AlterField(
            model_name='xtglzbx',
            name='zbms',
            field=models.CharField(max_length=512, null=True, verbose_name='指标描述'),
        ),
        migrations.AlterField(
            model_name='xtglzbx',
            name='zbwd',
            field=models.IntegerField(default=0, verbose_name='指标维度'),
        ),
    ]
