# Generated by Django 2.0 on 2019-09-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0010_auto_20190909_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglzbx',
            name='zbwd',
            field=models.CharField(max_length=64, null=True, verbose_name='指标维度'),
        ),
    ]
