# Generated by Django 2.0 on 2019-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0014_auto_20190911_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='uibejzg',
            name='zcjbbdrq',
            field=models.DateField(null=True, verbose_name='职称级别变动日期'),
        ),
    ]
