# Generated by Django 2.0 on 2019-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0017_auto_20190916_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uibebzks',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='uibejzg',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xshxbq',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglbqsz',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglbqwd',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtgljq',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='xtglzbx',
            name='create_user',
        ),
    ]
