# Generated by Django 2.0 on 2019-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0018_auto_20190919_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglbqwd',
            name='wdms',
            field=models.CharField(max_length=512, null=True, verbose_name='维度描述'),
        ),
    ]
