# Generated by Django 2.0 on 2019-09-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0020_auto_20190919_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uibebzks',
            old_name='sf',
            new_name='xf',
        ),
    ]
