# Generated by Django 2.0 on 2019-09-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0021_auto_20190919_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtglzbx',
            name='kqzt',
            field=models.IntegerField(choices=[(0, '停用'), (1, '启用')], default=0, verbose_name='开启状态'),
        ),
    ]
