# Generated by Django 2.0 on 2019-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0022_xtglzbx_kqzt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjzbzd',
            name='ywbm',
            field=models.CharField(default=None, max_length=32, verbose_name='英文表名'),
        ),
    ]
