# Generated by Django 2.0 on 2019-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0023_sjzbzd_ywbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjzbzd',
            name='ywbm',
            field=models.CharField(max_length=32, verbose_name='英文表名'),
        ),
    ]
