# Generated by Django 2.0 on 2019-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0024_auto_20190921_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglzbx',
            name='sjbxzs',
        ),
        migrations.AddField(
            model_name='xtglzbx',
            name='jsgz',
            field=models.CharField(max_length=32, null=True, verbose_name='计算规则'),
        ),
        migrations.AddField(
            model_name='xtglzbx',
            name='zdxz',
            field=models.CharField(max_length=32, null=True, verbose_name='字段选择'),
        ),
    ]
