# Generated by Django 2.0 on 2019-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0025_auto_20190921_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtglzbx',
            name='sjzb_id',
            field=models.CharField(default=1, max_length=32, verbose_name='总表id'),
        ),
    ]
