# Generated by Django 2.0 on 2019-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0026_xtglzbx_sjzb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglzbx',
            name='sjzb_id',
            field=models.CharField(max_length=32, verbose_name='总表id'),
        ),
    ]
