# Generated by Django 2.0 on 2019-09-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0027_auto_20190923_1602'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zcdj',
            table='jzg_zcdj',
        ),
    ]
