# Generated by Django 2.0 on 2019-09-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0028_auto_20190924_0926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xshxbq',
            table='bzks_xshxbq',
        ),
    ]
