# Generated by Django 2.0 on 2019-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0029_auto_20190924_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglbqsz',
            name='zbwd',
            field=models.CharField(max_length=32, verbose_name='指标维度'),
        ),
    ]
