# Generated by Django 2.0 on 2019-09-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0031_auto_20190926_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xtglbqsz',
            old_name='bqkfqx',
            new_name='kfqx',
        ),
    ]
