# Generated by Django 2.0 on 2019-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0032_auto_20190926_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglzbx',
            name='zbfl',
            field=models.IntegerField(choices=[(0, '单字段指标项'), (1, '多字段指标项')], default=0, verbose_name='指标分类'),
        ),
    ]
