# Generated by Django 2.0 on 2019-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0033_auto_20190926_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglbqsz',
            name='bqgz',
            field=models.CharField(max_length=512, verbose_name='标签规则'),
        ),
    ]
