# Generated by Django 2.0 on 2019-11-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0036_auto_20191112_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uibejzg',
            old_name='yjskcshms',
            new_name='yjskcskms',
        ),
    ]
