# Generated by Django 2.0 on 2019-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0038_auto_20191113_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='JzgZcxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwdm', models.CharField(max_length=16, verbose_name='职务代码')),
                ('zwmc', models.CharField(max_length=32, verbose_name='职务名称')),
                ('zujb', models.CharField(max_length=32, verbose_name='职务级别')),
            ],
            options={
                'verbose_name': '教职工职务分类',
                'verbose_name_plural': '教职工职务分类',
                'db_table': 'jzg_Zc',
            },
        ),
    ]
