# Generated by Django 2.0 on 2019-11-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0039_jzgzcxx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jzgzcxx',
            old_name='zujb',
            new_name='zwjb',
        ),
    ]
