# Generated by Django 2.0 on 2019-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0040_auto_20191114_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jzgzcxx',
            name='zwjb',
            field=models.CharField(max_length=32, null=True, verbose_name='职务级别'),
        ),
    ]
