# Generated by Django 2.0 on 2019-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0043_auto_20191114_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uibejzg',
            name='zcjb',
        ),
        migrations.AddField(
            model_name='uibejzg',
            name='zcbdrq',
            field=models.CharField(max_length=32, null=True, verbose_name='职称变动日期'),
        ),
        migrations.AddField(
            model_name='uibejzg',
            name='zcxxdm',
            field=models.CharField(max_length=32, null=True, verbose_name='职称信息代码'),
        ),
    ]
