# Generated by Django 2.0 on 2019-11-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0044_auto_20191114_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='BzksMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsh', models.CharField(max_length=128, verbose_name='学生号')),
                ('qkcs', models.IntegerField(verbose_name='翘课次数')),
                ('cjpm', models.IntegerField(verbose_name='成绩排名')),
                ('jdsf', models.IntegerField(verbose_name='绩点上浮')),
            ],
        ),
        migrations.AddField(
            model_name='xtglbqsz',
            name='bqSQL',
            field=models.CharField(max_length=512, null=True, verbose_name='标签规则SQL'),
        ),
    ]
