# Generated by Django 2.0 on 2019-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0045_auto_20191126_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='xshxbq',
            name='sfyx',
            field=models.IntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='是否有效'),
        ),
    ]
