# Generated by Django 2.0 on 2019-12-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0046_xshxbq_sfyx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uibebzks',
            name='by1',
        ),
        migrations.RemoveField(
            model_name='uibebzks',
            name='by2',
        ),
        migrations.RemoveField(
            model_name='uibebzks',
            name='sfsqxwzs',
        ),
        migrations.RemoveField(
            model_name='uibebzks',
            name='xslb',
        ),
    ]
