# Generated by Django 2.0 on 2019-12-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0049_auto_20191226_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='DW',
            fields=[
                ('yxdm', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='院系代码')),
                ('yxmc', models.CharField(max_length=32, verbose_name='院系名称')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portrait.DW')),
            ],
        ),
        migrations.AlterField(
            model_name='uibebzks',
            name='yxdm',
            field=models.CharField(choices=[('112', '外语学院'), ('101', '国际经济贸易学院'), ('114', '保险学院'), ('103', '英语学院'), ('104', '法学院'), ('109', '信息学院'), ('111', '金融学院'), ('121', '中国语言文学学院'), ('107', '公共管理学院'), ('102', '国际商学院'), ('124', '统计学院'), ('120', '国际关系学院')], max_length=16, null=True, verbose_name='院系代码'),
        ),
    ]
