# Generated by Django 2.0 on 2019-12-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0051_auto_20191226_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dw',
            name='author',
        ),
    ]
