# Generated by Django 2.0 on 2019-12-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0052_remove_dw_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibebzks',
            name='yxdm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portrait.DW'),
        ),
    ]
