# Generated by Django 2.0 on 2019-12-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0053_auto_20191226_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dw',
            old_name='yxdm',
            new_name='id',
        ),
    ]
