# Generated by Django 2.0 on 2019-12-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0054_auto_20191226_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dw',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='院系代码'),
        ),
    ]
