# Generated by Django 2.0 on 2019-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0055_auto_20191227_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uibebzks',
            name='yxdm',
        ),
        migrations.AddField(
            model_name='uibebzks',
            name='yxdm_id',
            field=models.IntegerField(choices=[('112', '外语学院'), ('101', '国际经济贸易学院'), ('114', '保险学院'), ('103', '英语学院'), ('104', '法学院'), ('109', '信息学院'), ('111', '金融学院'), ('121', '中国语言文学学院'), ('107', '公共管理学院'), ('102', '国际商学院'), ('124', '统计学院'), ('120', '国际关系学院')], null=True, verbose_name='院系代码'),
        ),
    ]
