# Generated by Django 2.0 on 2019-12-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0056_auto_20191227_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uibebzks',
            old_name='yxdm_id',
            new_name='yxdm',
        ),
    ]
