# Generated by Django 2.0 on 2019-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0057_auto_20191227_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibebzks',
            name='yxdm',
            field=models.IntegerField(choices=[(112, '外语学院'), (101, '国际经济贸易学院'), (114, '保险学院'), (103, '英语学院'), (104, '法学院'), (109, '信息学院'), (111, '金融学院'), (121, '中国语言文学学院'), (107, '公共管理学院'), (102, '国际商学院'), (124, '统计学院'), (120, '国际关系学院')], null=True),
        ),
    ]
