# Generated by Django 2.0 on 2019-12-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0058_auto_20191227_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibebzks',
            name='yxdm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portrait.DW'),
        ),
    ]
