# Generated by Django 2.0 on 2019-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0059_auto_20191227_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibebzks',
            name='yxdm',
            field=models.CharField(max_length=16, null=True, verbose_name='院系'),
        ),
    ]
