# Generated by Django 2.0 on 2019-12-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0060_auto_20191227_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uibebzks',
            old_name='yxdm',
            new_name='yx',
        ),
    ]
