# Generated by Django 2.0 on 2019-12-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0062_auto_20191230_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uibebzks',
            old_name='fdyh',
            new_name='fdy',
        ),
    ]
