# Generated by Django 2.0 on 2019-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0063_auto_20191230_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglbqsz',
            name='kfqx',
        ),
        migrations.AddField(
            model_name='xtglbqsz',
            name='bqqx',
            field=models.IntegerField(choices=[(0, '全部'), (1, '学生'), (2, '教师')], default=0, verbose_name='标签权限'),
        ),
    ]
