# Generated by Django 2.0 on 2019-12-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0064_auto_20191231_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JzgBm',
        ),
    ]
