# Generated by Django 2.0 on 2020-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0068_auto_20200109_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='BzksCETMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('kssj', models.CharField(max_length=64, verbose_name='考试时间')),
                ('tlcj', models.IntegerField(default=0, null=True, verbose_name='听力成绩')),
                ('ydcj', models.IntegerField(default=0, null=True, verbose_name='阅读成绩')),
                ('xzcj', models.IntegerField(default=0, null=True, verbose_name='写作成绩')),
                ('zfcj', models.IntegerField(default=0, null=True, verbose_name='总分成绩')),
                ('zfpm', models.IntegerField(default=0, null=True, verbose_name='总分排名')),
                ('zfpercentile', models.CharField(max_length=32, verbose_name='总分排名百分比')),
                ('zsmc', models.CharField(max_length=32, verbose_name='总分名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本专科四六级数据处理中间表',
                'verbose_name_plural': '本专科四六级数据处理中间表',
                'db_table': 'bzks_CET',
            },
        ),
        migrations.CreateModel(
            name='BzksTSJYMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('xb', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0)),
                ('zcs', models.IntegerField(default=0, null=True, verbose_name='总册数')),
                ('zcspm', models.IntegerField(default=0, null=True, verbose_name='总册数排名')),
                ('zcspetcentile', models.CharField(max_length=64, verbose_name='总册数排名百分比')),
                ('highlb', models.CharField(max_length=32, verbose_name='借阅最高册数类别')),
                ('highcs', models.IntegerField(default=0, null=True, verbose_name='借阅最高类别册数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
