# Generated by Django 2.0 on 2020-04-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0069_bzkscetmiddle_bzkstsjymiddle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bzkstsjymiddle',
            options={'verbose_name': '本专科图书借阅数据处理中间表', 'verbose_name_plural': '本专科图书借阅数据处理中间表'},
        ),
        migrations.AlterModelTable(
            name='bzkstsjymiddle',
            table='bzks_TSJY',
        ),
    ]
