# Generated by Django 2.0 on 2020-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0070_auto_20200410_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='BzksEKMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('txamt', models.CharField(max_length=32, null=True, verbose_name='消费总金额')),
                ('txamtpm', models.IntegerField(null=True, verbose_name='消费总金额排名')),
                ('txamtpetcentile', models.CharField(max_length=32, null=True, verbose_name='消费总金额排名百分比')),
                ('ztcs', models.IntegerField(default=0, null=True, verbose_name='当月澡堂次数')),
                ('stskcs', models.IntegerField(default=0, null=True, verbose_name='当月食堂刷卡次数')),
                ('stskcspm', models.IntegerField(default=0, null=True, verbose_name='当月食堂刷卡次数排名')),
                ('stskcspetcentile', models.CharField(max_length=32, null=True, verbose_name='当月食堂刷卡次数排名百分比')),
                ('zccs', models.IntegerField(default=0, null=True, verbose_name='当月早餐消费次数')),
                ('wccs', models.IntegerField(default=0, null=True, verbose_name='当月午餐消费次数')),
                ('wcxfcs', models.IntegerField(default=0, null=True, verbose_name='当月晚餐消费次数')),
                ('ystjyje', models.CharField(max_length=32, null=True, verbose_name='当月一食堂交易金额')),
                ('ystjyjepm', models.IntegerField(default=0, null=True, verbose_name='一食堂交易金额排名')),
                ('ystjyjepercent', models.CharField(max_length=32, null=True, verbose_name='一食堂交易金额排名所占百分比')),
                ('estjyje', models.CharField(max_length=32, null=True, verbose_name='当月二食堂交易金额')),
                ('estjyjepm', models.IntegerField(default=0, null=True, verbose_name='二食堂交易金额排名')),
                ('estjyjepercent', models.CharField(max_length=32, null=True, verbose_name='二食堂交易金额排名所占百分比')),
                ('sstjyje', models.CharField(max_length=32, null=True, verbose_name='当月三食堂交易金额')),
                ('sstjyjepm', models.IntegerField(default=0, null=True, verbose_name='三食堂交易金额排名')),
                ('sstjyjepercent', models.CharField(max_length=32, null=True, verbose_name='三食堂交易金额排名所占百分比')),
                ('qzstjyje', models.CharField(max_length=32, null=True, verbose_name='当月清真食堂交易金额')),
                ('qzstjyjepm', models.IntegerField(default=0, null=True, verbose_name='清真食堂交易金额排名')),
                ('qzstjyjepercent', models.CharField(max_length=32, null=True, verbose_name='清真食堂交易金额排名所占百分比')),
                ('hywmjyje', models.CharField(max_length=32, null=True, verbose_name='当月虹远物美白月光交易金额')),
                ('hywmjyjepm', models.IntegerField(default=0, null=True, verbose_name='虹远物美白月光交易金额排名')),
                ('hywmjyjepercent', models.CharField(max_length=32, null=True, verbose_name='虹远物美白月光交易金额排名所占百分比')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本专科E卡消费数据处理中间表',
                'verbose_name_plural': '本专科E卡消费数据处理中间表',
                'db_table': 'bzks_EK',
            },
        ),
    ]
