# Generated by Django 2.0 on 2020-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0071_bzksekmiddle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bzkscetmiddle',
            table='bzks_cet',
        ),
        migrations.AlterModelTable(
            name='bzksekmiddle',
            table='bzks_ek',
        ),
        migrations.AlterModelTable(
            name='bzkstsjymiddle',
            table='bzks_esjy',
        ),
    ]
