# Generated by Django 2.0 on 2020-04-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0072_auto_20200416_1000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bzkstsjymiddle',
            table='bzks_tsjy',
        ),
    ]
