# Generated by Django 2.0 on 2020-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0074_auto_20200610_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='UibeYjs',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('xh', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('xm', models.CharField(max_length=16, verbose_name='姓名')),
                ('xb', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0)),
                ('yx', models.CharField(max_length=16, null=True, verbose_name='院系')),
                ('xn', models.CharField(max_length=32, null=True, verbose_name='学年')),
                ('zy', models.CharField(max_length=64, null=True, verbose_name='专业')),
                ('dszgh', models.CharField(max_length=16, null=True, verbose_name='导师职工号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '研究生信息表',
                'verbose_name_plural': '研究生信息表',
                'db_table': 'yjs',
            },
        ),
    ]
