# Generated by Django 2.0 on 2020-06-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0075_uibeyjs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibeyjs',
            name='yx',
            field=models.CharField(max_length=64, null=True, verbose_name='院系'),
        ),
    ]
