# Generated by Django 2.0 on 2020-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0076_auto_20200612_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uibebzks',
            name='xm',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
    ]
