# Generated by Django 2.0 on 2020-09-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0077_auto_20200803_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BzksCETMiddle',
        ),
    ]
