# Generated by Django 2.0 on 2020-09-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0078_delete_bzkscetmiddle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BzksCETMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('kssj', models.CharField(max_length=64, verbose_name='考试时间')),
                ('tlcj', models.IntegerField(default=0, null=True, verbose_name='听力成绩')),
                ('ydcj', models.IntegerField(default=0, null=True, verbose_name='阅读成绩')),
                ('xzcj', models.IntegerField(default=0, null=True, verbose_name='写作成绩')),
                ('zhcj', models.IntegerField(default=0, null=True, verbose_name='综合成绩')),
                ('zfcj', models.IntegerField(default=0, null=True, verbose_name='总分成绩')),
                ('zfpm', models.IntegerField(default=0, null=True, verbose_name='总分排名')),
                ('zfpercentile', models.CharField(max_length=32, verbose_name='总分排名百分比')),
                ('zsmc', models.CharField(max_length=32, verbose_name='总分名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本专科四六级数据处理中间表',
                'verbose_name_plural': '本专科四六级数据处理中间表',
                'db_table': 'bzks_cet',
            },
        ),
    ]
