# Generated by Django 2.0 on 2020-09-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0079_bzkscetmiddle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtglzbx',
            name='zbxmc',
        ),
    ]
