# Generated by Django 2.0 on 2020-09-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0082_auto_20200917_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xshxbq',
            options={'verbose_name': '用户画像之学生画像', 'verbose_name_plural': '用户画像之学生画像'},
        ),
        migrations.RemoveField(
            model_name='xshxbq',
            name='bq',
        ),
        migrations.AddField(
            model_name='xshxbq',
            name='bqid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bqsz', to='portrait.XtglBqsz'),
        ),
    ]
