# Generated by Django 2.0 on 2020-09-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0083_auto_20200923_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xshxbq',
            name='bqsm',
        ),
    ]
