# Generated by Django 2.0 on 2020-09-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0084_remove_xshxbq_bqsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xshxbq',
            name='bqid',
        ),
        migrations.AddField(
            model_name='xshxbq',
            name='bq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xshxbq', to='portrait.XtglBqsz'),
        ),
    ]
