# Generated by Django 2.0 on 2020-09-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0085_auto_20200923_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xshxbq',
            name='bqqx',
        ),
    ]
