# Generated by Django 2.0 on 2020-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0086_remove_xshxbq_bqqx'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtglbqsz',
            name='sfsc',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='是否删除'),
        ),
    ]
