# Generated by Django 2.0 on 2020-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0087_xtglbqsz_sfsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtglbqsz',
            name='bqqx',
            field=models.IntegerField(choices=[(0, '全部'), (1, '教师'), (2, '学生')], default=0, verbose_name='标签权限'),
        ),
    ]
